In [3]:
import pandas as pd
df = pd.read_csv('filing-counts.csv')
def load_and_process(filing_counts):
    df = (
        pd.read_scv('filing_counts.csv')
        .drop('for_total',axis=1)
        .drop('case_action',axis=1)
        .assign(case_type_state=lambda x: x['case_type']+x['state'])
    )
    return df
df.head(10)

,state,year,case_action,case_type,age_group,count,for_total
0,Alaska,2020,Ambiguous,G+C+Joint,Adults+Minors,1171,Y
1,Alaska,2019,Ambiguous,G+C+Joint,Adults+Minors,1084,Y
2,Alaska,2018,Ambiguous,G+C+Joint,Adults+Minors,1227,Y
3,Alaska,2017,Ambiguous,G+C+Joint,Adults+Minors,1090,Y
4,Arizona,2020,Ambiguous,Guardianship ONLY,Adults ONLY,2520,Y
5,Arizona,2020,Ambiguous,Guardianship ONLY,Minors ONLY,2871,N
6,Arizona,2020,Ambiguous,Conservatorship ONLY,Adults ONLY,3485,N
7,Arizona,2020,Ambiguous,Conservatorship ONLY,Minors ONLY,1365,N
8,Arizona,2019,Ambiguous,Guardianship ONLY,Adults ONLY,2383,Y
9,Arizona,2019,Ambiguous,Guardianship ONLY,Minors ONLY,3608,N