In [16]:
import pandas as pd
df = pd.read_csv('filing_counts.csv')
def load_and_process(filing_counts):
    df = (
        pd.read_scv('filing_counts.csv')
        .drop('for_total',axis=1)
        .drop('case_action',axis=1)
        .assign(case_type_state=lambda x: x['case_type']+x['state'])
    )
    return df

df

,state,year,case_action,case_type,age_group,count,for_total
0,Alaska,2020,Ambiguous,G+C+Joint,Adults+Minors,1171,Y
1,Alaska,2019,Ambiguous,G+C+Joint,Adults+Minors,1084,Y
2,Alaska,2018,Ambiguous,G+C+Joint,Adults+Minors,1227,Y
3,Alaska,2017,Ambiguous,G+C+Joint,Adults+Minors,1090,Y
4,Arizona,2020,Ambiguous,Guardianship ONLY,Adults ONLY,2520,Y
...,...,...,...,...,...,...,...
375,Wisconsin,2020,Initiated+Reopened,G+C+Joint,Adults+Minors,5624,Y
376,Wisconsin,2019,Initiated+Reopened,G+C+Joint,Adults+Minors,6051,Y
377,Wisconsin,2018,Initiated+Reopened,G+C+Joint,Adults+Minors,6180,Y
378,Wisconsin,2017,Initiated+Reopened,G+C+Joint,Adults+Minors,6196,Y
379,Wisconsin,2016,Initiated+Reopened,G+C+Joint,Adults+Minors,6030,Y